= Programming meets story telling

== Introduction

== Arrays can twist your brain
=== Find the Max Sum of a Contiguous Sequence
Input - [1, -1, 0]
Result - 1

Input - [-1, -6, -5, 0]
Result - 0

Input - [1, 1, 1, -2, 4, 5]
Result - 10

==== How to solve in a single loop
This talks about contiguous sequence. Imagine this like some kind of sort. 
Hopefully a single pass i.e O(N) is enough

==== When to include & when to avoid negatives
Relax. Try solving the max sum part. Use the canonical Comparison & Swap logic 
FIRST to make a headstart.

==== Should this be a sliding window like solution
This is more than slide. It becomes longer till the sum grows as well as
reduces. Who knows the next item will grow the sum further. 

NOTE: It becomes tricky when one starts to think about multiple combinations
that this problem offers. Only one combination can be the final solution.

==== Is there any Trick?
Consider two variables Max_SUM & Current_SUM
Do not let the Current_SUM to be less than 0 Within A Loop

NOTE: This helps us manage multitude of combinations

==== Remember
[source,go]
----
func MaxSum(given []int) int {
  if len(given) == 0 return 0
  if len(given) == 1 return given[0]
  
  // IMP - no need to init MIN INT
  var maxSum = given[0]
  var currMax = 0
  for (i:=0;i<len(given)-1;i++) {
    currMax += given[i]
    if maxSum < currMax {
      maxSum = currMax
    } else if currMax < 0 { // else if is IMP
      currMax = 0
    }
  }
  return maxSum
}
----

== Inspirations
- https://github.com/bbatsov/clojure-style-guide[clojure-style-guide] has inspired this styling
