.PHONY: string
string:
	rustc string.rs -o tmp/string

.PHONY: hello
hello:
	rustc hello.rs -o tmp/hello

.PHONY: move
move:
	rustc move.rs -o tmp/move

.PHONY: slice
slice:
	rustc slice.rs -o tmp/slice
